-- =====================================================
-- Import 127 Properti dari Excel QSE Tracker
-- Jalankan di Supabase SQL Editor
-- Hapus dulu sample data sebelumnya jika ada
-- =====================================================

-- Hapus data sample sebelumnya
DELETE FROM properties;

-- Helper function untuk mapping kota ke region & provinsi
-- Insert 127 properti

INSERT INTO properties (code, name, brand, city, province, region, status) VALUES
('SUR0741','RedDoorz @ Siwalankerto Surabaya','RedDoorz','Surabaya','Jawa Timur','Jawa','Active'),
('JAK5423','RedDoorz @ Pavilion Residence Cikarang','RedDoorz','Cikarang','Jawa Barat','Jawa','Active'),
('SEMA0040','RedDoorz @ Tasneem Puspowarno Semarang','RedDoorz','Semarang','Jawa Tengah','Jawa','Active'),
('SEM2039','RedDoorz Near Gajah Mada Street Semarang','RedDoorz','Semarang','Jawa Tengah','Jawa','Active'),
('MED1906','RedDoorz @ Jamin Ginting Medan','RedDoorz','Medan','Sumatera Utara','Sumatera','Active'),
('MAL13679','Urbanview Hotel de Kopen Malang by RedDoorz','Urbanview','Malang','Jawa Timur','Jawa','Active'),
('PAL1096','RedDoorz near Siloam Hospital Palembang','RedDoorz','Palembang','Sumatera Selatan','Sumatera','Active'),
('BANA0235','Urbanview Hotel Sakura Bandung','Urbanview','Bandung','Jawa Barat','Jawa','Active'),
('JAM43276','RedDoorz @ Jalan HOS Cokroaminoto Jambi','RedDoorz','Jambi','Jambi','Sumatera','Active'),
('BAN1624','RedDoorz @ Cikutra 3','RedDoorz','Bandung','Jawa Barat','Jawa','Active'),
('MAK38312','RedDoorz near Mall Ratu Indah 3','RedDoorz','Makassar','Sulawesi Selatan','Sulawesi','Active'),
('MAL3627','RedDoorz @ Jalan Kedawung','RedDoorz','Malang','Jawa Timur','Jawa','Active'),
('MAL8046','RedDoorz @ Simpang Borobudur','RedDoorz','Malang','Jawa Timur','Jawa','Active'),
('YOG1486','RedDoorz near RS Sarjito Yogyakarta 2','RedDoorz','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('MED8830','RedDoorz @ Seindo Hotel Medan','RedDoorz','Medan','Sumatera Utara','Sumatera','Active'),
('YOG1315','RedDoorz near AMIKOM Yogyakarta','RedDoorz','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('MAJA0017','RedDoorz Plus @ Hotel Putrajaya','RedDoorz','Majalengka','Jawa Barat','Jawa','Active'),
('YOG1175','RedDoorz near Hartono Mall 3','RedDoorz','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('JAK5424','RedDoorz @ Iodium Residence Cikarang','RedDoorz','Cikarang','Jawa Barat','Jawa','Active'),
('MAL5552','RedDoorz @ Karangploso 2','RedDoorz','Malang','Jawa Timur','Jawa','Active'),
('JAK1404','RedDoorz Plus near Mall Slipi Jaya','RedDoorz','Jakarta','DKI Jakarta','Jawa','Active'),
('GAR1818','RedDoorz Plus @ Otista Garut','RedDoorz','Garut','Jawa Barat','Jawa','Active'),
('MAK3360','RedDoorz @ Graha Cemerlang Maros','RedDoorz','Makassar','Sulawesi Selatan','Sulawesi','Active'),
('JAKA0386','RedDoorz near Sarinah Mall','RedDoorz','Jakarta','DKI Jakarta','Jawa','Active'),
('SURA0067','RedDoorz @ Graha 99 Simomulyo','RedDoorz','Surabaya','Jawa Timur','Jawa','Active'),
('TASA0052','RedDoorz @ Jalan Siliwangi Tasikmalaya','RedDoorz','Tasikmalaya','Jawa Barat','Jawa','Active'),
('YOGA0050','Urbanview Omah Eka Santi by RedDoorz','Urbanview','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('JAK3723','RedDoorz Plus Syariah near Mall Pondok Indah','RedDoorz','Jakarta','DKI Jakarta','Jawa','Active'),
('SEM3283','RedDoorz @ Jalan Kartini Semarang','RedDoorz','Semarang','Jawa Tengah','Jawa','Active'),
('YOG13535','RedDoorz @ Golden Inn Tugu Yogyakarta','RedDoorz','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('BAN1280','RedDoorz near Jatinangor Town Square','RedDoorz','Bandung','Jawa Barat','Jawa','Active'),
('TANA0018','RedDoorz @ Victory Homestay Karawaci','RedDoorz','Tangerang','Banten','Jawa','Active'),
('MAKA0132','RedDoorz near Universitas Hasanuddin Makassar','RedDoorz','Makassar','Sulawesi Selatan','Sulawesi','Active'),
('BAN2826','RedDoorz near Alun Alun Bandung 2','RedDoorz','Bandung','Jawa Barat','Jawa','Active'),
('BALA0545','RedDoorz @ Hotel Dewata Indah Denpasar','RedDoorz','Denpasar','Bali','Bali & Nusa Tenggara','Active'),
('KEN2132','RedDoorz Plus @ Hotel Srikandi Kendari','RedDoorz','Kendari','Sulawesi Tenggara','Sulawesi','Active'),
('BAN1685','RedDoorz Plus @ Dago Pojok 3','RedDoorz','Bandung','Jawa Barat','Jawa','Active'),
('MAL2042','RedDoorz @ Soekarno Hatta Indah','RedDoorz','Malang','Jawa Timur','Jawa','Active'),
('SEMA0029','RedDoorz near Kawasan Bandara Ahmad Yani Semarang 2','RedDoorz','Semarang','Jawa Tengah','Jawa','Active'),
('BAN2112','RedDoorz near Setrasari Mall 4','RedDoorz','Bandung','Jawa Barat','Jawa','Active'),
('JAK6606','Reddoorz Syariah Plus @ Wisma Bougenville Karawaci','RedDoorz','Tangerang','Banten','Jawa','Active'),
('JAK8018','RedDoorz @ Taman Royal Tangerang','RedDoorz','Tangerang','Banten','Jawa','Active'),
('YOG13016','Sans Hotel Nagari Malioboro','Sans Hotel','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('YOG1585','RedDoorz near AMIKOM Yogyakarta 2','RedDoorz','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('BANA0293','Sans Stay Skyland Pasteur Bandung','Sans Hotel','Bandung','Jawa Barat','Jawa','Active'),
('BAN0135','RedDoorz Plus near Parahyangan University','RedDoorz','Bandung','Jawa Barat','Jawa','Active'),
('YOGA0791','RedDoorz near UGM Kaliurang 2 Yogyakarta','RedDoorz','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('TEGA0073','Urbanview Hotel near Alun Alun Tegal','Urbanview','Tegal','Jawa Tengah','Jawa','Active'),
('PEKA0098','Sans Vibes Viandara Pekanbaru','Sans Hotel','Pekanbaru','Riau','Sumatera','Active'),
('NGAA0069','RedDoorz Near Stasiun Nganjuk','RedDoorz','Nganjuk','Jawa Timur','Jawa','Active'),
('YOGA0669','Urbanview Hotel Simple near Pakuwon Mall Jogja','Urbanview','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('BATA0207','SANS Vibes d Grande Hotel Batam','Sans Hotel','Batam','Kepulauan Riau','Sumatera','Active'),
('BANA0201','Urbanview near Syamsudin Noor Airport Banjarbaru','Urbanview','Banjarbaru','Kalimantan Selatan','Kalimantan','Active'),
('JAKA0717','Urbanview Hotel Mitra near Grand Indonesia','Urbanview','Jakarta','DKI Jakarta','Jawa','Active'),
('MEDA0217','RedDoorz near Gajah Mada Park Medan','RedDoorz','Medan','Sumatera Utara','Sumatera','Active'),
('BALA0971','The Lavana Allena Living Bali','Lavana','Denpasar','Bali','Bali & Nusa Tenggara','Active'),
('SURA0184','Urbanview Hotel Syariah Graha 8 Bubutan Surabaya','Urbanview','Surabaya','Jawa Timur','Jawa','Active'),
('MEDA0191','RedDoorz Hostel @ Finest Medan','Sans Hotel','Medan','Sumatera Utara','Sumatera','Active'),
('YOG1124','RedDoorz near XT Square Yogyakarta','RedDoorz','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('BALA0952','Urbanview Noja Guest House near Living World Denpasar','Urbanview','Denpasar','Bali','Bali & Nusa Tenggara','Active'),
('MEDA0201','Urbanview Hotel Grand Mohaga Medan','Urbanview','Medan','Sumatera Utara','Sumatera','Active'),
('PANA0036','Urbanview Hotel Wongso Pangkal Pinang','Urbanview','Pangkal Pinang','Bangka Belitung','Sumatera','Active'),
('MALA0131','RedDoorz near Malang Creative Center','RedDoorz','Malang','Jawa Timur','Jawa','Active'),
('LAMA0389','RedDoorz Plus JIB Hotel Lampung','RedDoorz','Bandar Lampung','Lampung','Sumatera','Active'),
('ACEA0086','Reddoorz Syariah Medina House Aceh','RedDoorz','Banda Aceh','Aceh','Sumatera','Active'),
('BATA0191','Urbanview Hotel X Ten Harbour Bay Batam','Sans Hotel','Batam','Kepulauan Riau','Sumatera','Active'),
('YOGA0201','RedDoorz @ Savitri Hotel','RedDoorz','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('PEKA0111','RedDoorz Hotel Baaraka near Living World','RedDoorz','Pekanbaru','Riau','Sumatera','Active'),
('JAMA0245','RedDoorz near Bandar Udara Jambi','RedDoorz','Jambi','Jambi','Sumatera','Active'),
('SUKA0070','RedDoorz near Tugu Kartasura 2','RedDoorz','Surakarta','Jawa Tengah','Jawa','Active'),
('MAKA0173','Urbanview Hotel near Pantai Losari Makassar','Urbanview','Makassar','Sulawesi Selatan','Sulawesi','Active'),
('BANA0307','Sans Vibes Diemdi Kiaracondong Bandung','Sans Hotel','Bandung','Jawa Barat','Jawa','Active'),
('MEDA0263','RedDoorz @ Wika Wiki Homestay','RedDoorz','Medan','Sumatera Utara','Sumatera','Active'),
('BANA0429','Sunerra Express Grand Viveana Bandung','Sans Hotel','Bandung','Jawa Barat','Jawa','Active'),
('YOGA0584','RedDoorz @ Griya Mbah Rono Malioboro','RedDoorz','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('BALA0895','Sans Vibes Hotel Seminyak','Sans Hotel','Badung','Bali','Bali & Nusa Tenggara','Active'),
('BALA0831','Sans Vibes Puri Mango Hotel Sanur','Sans Hotel','Denpasar','Bali','Bali & Nusa Tenggara','Active'),
('BALA0918','Lilis Aksito Akusara by Lavana','Lavana','Denpasar','Bali','Bali & Nusa Tenggara','Active'),
('TEGA0101','RedDoorz near RSUD Kardinah Tegal','RedDoorz','Tegal','Jawa Tengah','Jawa','Active'),
('JAMA0227','Urbanview Hotel Cosmo Jambi','Urbanview','Jambi','Jambi','Sumatera','Active'),
('MEDA0032','Sans Hotel Finest Medan','Sans Hotel','Medan','Sumatera Utara','Sumatera','Active'),
('BALA0121','Urbanview Hotel near BSCC DOME Balikpapan','Urbanview','Balikpapan','Kalimantan Timur','Kalimantan','Active'),
('JAK2604','RedDoorz Syariah near Jatisampurna Hospital','RedDoorz','Bekasi','Jawa Barat','Jawa','Active'),
('JAK0972','RedDoorz Plus @ Thamrin','RedDoorz','Jakarta','DKI Jakarta','Jawa','Active'),
('MATA0045','RedDoorz @ Tienery Guest House','RedDoorz','Mataram','Nusa Tenggara Barat','Bali & Nusa Tenggara','Active'),
('JAMA0253','RedDoorz @ Qaireen Living Jambi','RedDoorz','Jambi','Jambi','Sumatera','Active'),
('PEKA0114','Sans Hotel Bliss Pekanbaru','Sans Hotel','Pekanbaru','Riau','Sumatera','Active'),
('BALA0911','Urbanview Hotel Lilis Cempaka Mas Guesthouse','Urbanview','Balikpapan','Kalimantan Timur','Kalimantan','Active'),
('BANA0239','RedDoorz Plus @ Jalan Raya Lembang','RedDoorz','Bandung','Jawa Barat','Jawa','Active'),
('YOGA0530','Sans Hotel Beskalan Malioboro','Sans Hotel','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('BANA0195','RedDoorz near Bandara Depati Amir','RedDoorz','Pangkal Pinang','Bangka Belitung','Sumatera','Active'),
('BANA0444','RedDoorz Sanira near Gedung Sate Bandung','Urbanview','Bandung','Jawa Barat','Jawa','Active'),
('SURA0187','Sans Vibes Hotel Syariah Graha 100 Gubeng Surabaya','Sans Hotel','Surabaya','Jawa Timur','Jawa','Active'),
('YOGA0787','RedDoorz near UGM Kaliurang Yogyakarta','RedDoorz','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('BEKA0239','SANS Vibes Hotel Igloo Cikarang','Sans Hotel','Bekasi','Jawa Barat','Jawa','Active'),
('PEMA0021','RedDoorz near Alun Alun Pemalang','RedDoorz','Pemalang','Jawa Tengah','Jawa','Active'),
('MAL8952','RedDoorz @ Gangnam Hotel near Mall Olympic Garden','RedDoorz','Malang','Jawa Timur','Jawa','Active'),
('YOGA0753','RedDoorz Plus @ Sisingamangaraja Prawirotaman Yogyakarta','RedDoorz','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('BANA0374','Urbanview Hotel near Paris Van Java Mall','Urbanview','Bandung','Jawa Barat','Jawa','Active'),
('MALA0186','RedDoorz near RS Panti Nirmala Malang','RedDoorz','Malang','Jawa Timur','Jawa','Active'),
('BATA0211','Urbanview SJ Inn Sukajadi near K Square Batam','Urbanview','Batam','Kepulauan Riau','Sumatera','Active'),
('SURA0227','Urbanview Mastrip Karangpilang Surabaya','Urbanview','Surabaya','Jawa Timur','Jawa','Active'),
('MAK1531','RedDoorz Plus @ Boulevard Panakkukang','RedDoorz','Makassar','Sulawesi Selatan','Sulawesi','Active'),
('JAK0913','RedDoorz Plus near Cilandak Town Square 2','RedDoorz','Jakarta','DKI Jakarta','Jawa','Active'),
('MED2479','RedDoorz Plus near Istana Maimun Medan','RedDoorz','Medan','Sumatera Utara','Sumatera','Active'),
('TASA0012','Urbanview Hotel Crown Tasikmalaya by RedDoorz','Urbanview','Tasikmalaya','Jawa Barat','Jawa','Active'),
('YOGA0468','Urbanview Hotel Grand Surya Yogyakarta','Urbanview','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('SURA0015','Marcello Residence Siwalankerto near Petra University','Urbanview','Surabaya','Jawa Timur','Jawa','Active'),
('MED8344','RedDoorz @ CBD Polonia Medan','RedDoorz','Medan','Sumatera Utara','Sumatera','Active'),
('BAN1649','RedDoorz near Lembang Park & Zoo 2','RedDoorz','Bandung','Jawa Barat','Jawa','Active'),
('LAMA0098','RedDoorz near UBL Lampung','RedDoorz','Bandar Lampung','Lampung','Sumatera','Active'),
('SOLA0110','RedDoorz near Jalan Slamet Riyadi Solo','RedDoorz','Surakarta','Jawa Tengah','Jawa','Active'),
('MED4816','RedDoorz Plus @ Simpang USU Medan','RedDoorz','Medan','Sumatera Utara','Sumatera','Active'),
('JAK1929','RedDoorz Plus near Senayan City','RedDoorz','Jakarta','DKI Jakarta','Jawa','Active'),
('MADA0048','RedDoorz Syariah near Stasiun Madiun 2','Urbanview','Madiun','Jawa Timur','Jawa','Active'),
('YOGA0622','RedDoorz near Lippo Mall Yogyakarta 3','RedDoorz','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('BANA0314','RedDoorz Hostel @ Kiara Cozy Kircon Bandung','RedDoorz','Bandung','Jawa Barat','Jawa','Active'),
('BALA0914','Urbanview Hotel Lilis Ikvala Radha','Urbanview','Balikpapan','Kalimantan Timur','Kalimantan','Active'),
('JAK1852','RedDoorz Plus near Ancol','RedDoorz','Jakarta','DKI Jakarta','Jawa','Active'),
('YOGA0304','Urbanview Hotel Pondok Anggun Yogyakarta','Urbanview','Yogyakarta','DI Yogyakarta','Jawa','Active'),
('GAR7945','RedDoorz Resort near Darajat Garut','RedDoorz','Garut','Jawa Barat','Jawa','Active'),
('BALA1116','Urbanview Hotel @ Tanjung Benoa Bali','Urbanview','Badung','Bali','Bali & Nusa Tenggara','Active'),
('MED5831','RedDoorz @ Jotel Guest House','RedDoorz','Medan','Sumatera Utara','Sumatera','Active'),
('PEKA0037','RedDoorz Syariah near RSUD Kajen Pekalongan','RedDoorz','Pekalongan','Jawa Tengah','Jawa','Active'),
('JAK78745','Eascot Hotel Redpartner','RedDoorz','Jakarta','DKI Jakarta','Jawa','Active'),
('BAL1119','RedDoorz Near Terminal Batu Ampar Balikpapan','RedDoorz','Balikpapan','Kalimantan Timur','Kalimantan','Active'),
('JAK80126','Benhill Syariah Residence 2 Mitra RedDoorz','RedDoorz','Jakarta','DKI Jakarta','Jawa','Active')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  city = EXCLUDED.city,
  province = EXCLUDED.province,
  region = EXCLUDED.region,
  status = EXCLUDED.status;

-- Verifikasi jumlah
SELECT COUNT(*) as total_properties, 
       COUNT(DISTINCT city) as total_cities,
       COUNT(DISTINCT region) as total_regions
FROM properties;
